# Generated by Django 4.0.3 on 2022-06-03 20:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.chat'),
        ),
        migrations.AlterField(
            model_name='text',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
