# Generated by Django 4.0.3 on 2022-06-02 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='last_message',
            field=models.TextField(default='No Messages Yet'),
        ),
    ]
