# Generated by Django 4.0.5 on 2022-06-04 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_alter_text_chat_alter_text_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='photo',
        ),
        migrations.AddField(
            model_name='room',
            name='photos',
            field=models.JSONField(default=[]),
        ),
    ]
