# Generated by Django 4.0.5 on 2022-06-04 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_remove_room_photo_room_photos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='rooms',
        ),
        migrations.AddField(
            model_name='post',
            name='rooms',
            field=models.JSONField(default=[]),
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
