# Generated by Django 4.0.5 on 2022-06-05 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_remove_post_rooms_post_rooms_delete_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='post',
            name='rooms',
            field=models.JSONField(default=[[]]),
        ),
    ]
