# Generated by Django 4.0.3 on 2022-05-30 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_remove_post_photo_alter_chat_id_alter_post_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='rooms',
            field=models.ManyToManyField(null=True, to='API.room'),
        ),
    ]
