# Generated by Django 4.0.3 on 2022-05-30 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_alter_post_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
