# Generated by Django 4.0.5 on 2022-06-05 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_remove_post_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='post',
            name='rooms',
        ),
    ]
