# Generated by Django 4.0.3 on 2022-05-30 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_post_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='rooms',
            field=models.ManyToManyField(blank=True, to='API.room'),
        ),
    ]
