# Generated by Django 4.0.5 on 2022-06-05 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_remove_post_photo_remove_post_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.JSONField(default=[]),
        ),
        migrations.AddField(
            model_name='post',
            name='rooms',
            field=models.JSONField(default=[[]]),
        ),
    ]
