# Generated by Django 4.0.5 on 2022-06-05 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_post_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
    ]
