# Generated by Django 4.0.5 on 2022-06-05 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0011_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.CharField(default='House', max_length=200),
            preserve_default=False,
        ),
    ]
